@startuml

start

partition "Session Life Cycle" {

:init_session();

repeat
rectangle "Request/Response" {
  :wrap_req_func();
  -> req;
  :Send and Receive;
  -> rsp;
}

:update_session();

repeat while (should_stop_session())  is (True) not (False)

}
stop


@enduml
