name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') > pylint_output.txt || true
        tail -n 10 pylint_output.txt

    - name: Check pylint score
      run: |
        score=$(tail -n 10 pylint_output.txt | grep "Your code has been rated at" | awk '{print $7}' | cut -d'/' -f1)
        min_score=8.0
        if (( $(echo "$score < $min_score" | bc -l) )); then
          echo "Pylint score ($score) is below the minimum required score ($min_score)."
          exit 1
        else
          echo "Pylint score ($score) meets the minimum required score ($min_score)."
        fi
